services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_NAME: "${NEXT_PUBLIC_NAME}"
        NEXT_PUBLIC_SITE_LANG: "${NEXT_PUBLIC_SITE_LANG}"
        NEXT_PUBLIC_PRERENDER_LIMIT: "${NEXT_PUBLIC_PRERENDER_LIMIT}"
        NEXT_PUBLIC_BASE: "${NEXT_PUBLIC_BASE}"
        NEXT_PUBLIC_INDEX: "${NEXT_PUBLIC_INDEX}"
        NEXT_PUBLIC_RATES_MIN: "${NEXT_PUBLIC_RATES_MIN}"
        NEXT_PUBLIC_RATES_RENDER_MIN: "${NEXT_PUBLIC_RATES_RENDER_MIN}"
        NEXT_PUBLIC_TELEGRAM_SUPPORT: "${NEXT_PUBLIC_TELEGRAM_SUPPORT}"
        NEXT_PUBLIC_TELEGRAM_BOT: "${NEXT_PUBLIC_TELEGRAM_BOT}"
        NEXT_PUBLIC_TELEGRAM_CHAT: "${NEXT_PUBLIC_TELEGRAM_CHAT}"
        NEXT_PUBLIC_GOOGLE_MAPS_KEY: "${NEXT_PUBLIC_GOOGLE_MAPS_KEY}"
        USE_INTERNAL: "${USE_INTERNAL}"
        INTERNAL_CMS_URL: "${INTERNAL_CMS_URL}"
        INTERNAL_SERVER_URL: "${INTERNAL_SERVER_URL}"
        INTERNAL_CONVERTER_URL: "${INTERNAL_CONVERTER_URL}"
    environment:
      USE_INTERNAL: "${USE_INTERNAL}"
    ports:
      - "3000:3000"
    restart: always
